const DEFAULT_ERR: string = 'Oops I ran into a problem. Go find Lemons.'

const DISCORD_TOKEN: string = 'DISCORD_TOKEN'
const AWS_ACCESS_KEY_ID: string = 'AWS_ACCESS_KEY_ID'
const AWS_SECRET_ACCESS_KEY: string = 'AWS_SECRET_ACCESS_KEY'
const AWS_REGION: string = 'AWS_REGION'

const REQ_CONFIG = [
  DISCORD_TOKEN,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_REGION
]

export {
  AWS_ACCESS_KEY_ID,
  AWS_REGION,
  AWS_SECRET_ACCESS_KEY,
  DEFAULT_ERR,
  DISCORD_TOKEN,
  REQ_CONFIG
}
